### ISSUE TITLE
DSL ( Domain-Specific-Language )

### ISSUE THREAD

**Issue by yklaus** [kenu/springstudy2013#16]
어떤 한 분야에 특화된 언어로써 예를 들어 

" Gradle은 Groovy DSL을 기본으로 한다. " 라고 하면 Gradle을 위해서 만들어진 특수언어다

라고 생각하면 편할 것입니다.

이를 응용해서 커스터 마이징 하게되면 한글로도 코딩이 가능하게 만들 수도 있습니다..

http://it.gilbird.com/textyle/8318

위 사이트는 Groovy DSL을 이용한 한국어로 코딩을 하는 ...... 내용 설명

-> Domain-Specific Language(DSL)은 특정 도메인에 특화된 비교적 작고 간단한 프로그래밍 언어이다. 도메인 문제를 해결 할 때, 문제 해결 아이디어와 최대한 유사한 형태의 문법으로 프로그래밍 할 수 있도록 하는 것이 주요 컨셉트이다.
DSL의 반대 개념은 General Purpose Language(GPL)이며 Java나 C++같은 보편적인 언어를 지칭한다. GPL로는 컴퓨터로 해결 가능한 모든 종류의 문제를 풀 수 있지만 그것이 항상 최선의 방법은 아니며 DSL 바로 그 특정한 종류(도메인 영역)의 문제를 해결하기에 더 적합한 언어가 되는 것을 그 목적으로 한다.
이클립스에서는 Xtext를 이용하여 DSL을 정의하고 에디터 및 DSL 기반 인터프리터 또는 제네레이터를 공급할 수 있다. GPL 중에서도 Java Script등과 같은 다이니믹 타이핑 언어등을 개발할 때에는 DLTK를 이용할 수 있다.
- 위클립스 - 에서 참조
- 위클립스 : 이클립스 한국어 위키
- http://eclipse.or.kr/wiki/

**Comment by bluewbear** [comment]
좋은 정보 감사합니다~ 👍
